### ISSUE TITLE
Enhance TCK to allow execution of Signature Test with Java during full Maven build

### ISSUE THREAD

**Issue by scottkurz** [eclipse-ee4j/batch-tck#15]
The TCK uses the **jakarta.batch.official.tck** to build the official TCK zip and the **com.ibm.jbatch.tck.dist.exec** to execute the TCK against the 'jbatch' implementation.    But the signature test portion only works when running Java 8 (so we disable the Java 11 piece with the enforcer plugin).

The Java 11 signature tests can be run by doing the jimage extract (see TCK reference guide), then doing:

` mvn ...  -Djava.base.sigtest.path="$EXTRACT_DIR\java.base"  `

but it would be nice to automate the extraction and this execution.

**Comment by scottkurz** [comment]
Also consider switching to this:  https://github.com/jtulach/netbeans-apitest#readme   recommended by Scott Stark, who said they're using this for BVal.

**Comment by OndroMih** [comment]
I had a look at https://github.com/jtulach/netbeans-apitest#readme but it has some severe limitations. It validates the signature in classes on the classpath (e.g. in maven dependencies) and doesn't allow specifying a separate classpath for sigtest. This is what we do with the Ant task currently. BVal only uses it to generate the signature file but instructs to run it from a separate Maven project to run the sigtest for TCK verification. It's the same thing as we have now, just with Maven instead of Ant.

I'll try to add support for Java 11 by automating the manual steps with Ant in Maven.
