### ISSUE TITLE
Create pattern to no-op Batch+CDI integration tests when CDI is not present

### ISSUE THREAD

**Issue by scottkurz** [eclipse-ee4j/batch-tck#20]
The proposal here starts with the assumption that Jakarta specs don't include optional features.  
To me that suggests every implementation needs to pass 100% of the tests.

Here is a pattern that could maybe be used:

```java
static boolean cdiEnabled;

@BeforeAll  // JUnit 5
public void setup() {
    cdiEnabled =  isCDIEnabled();  
}

@Test 
public void testFunctionOne() {
     if (!cdiEnabled) {
        // log and return, we no-op and pass the test
     }  else {
       // go on to do the real test. 
     } 
}
```

I'm thinking `isCDIEnabled()` runs a special "CDI detection" batch job since that would make it more transparent that the true/false value is supposed to be determined via a standard way, rather than invent some special switch or TCK SPI that could arbitrarily return `false` to skip these tests for whatever reason.

**Comment by rmannibucau** [comment]
Makes a compliant (green test) impl not portable in terms of behavior. It is saner to group tests and have kind of profiles. This way impl can be compliant in regards of a profile.

**Comment by scottkurz** [comment]
I agree this would not be an especially sane way to construct a test suite from scratch.  But do the Jakarta processes allow for something like a "CDI profile" for a spec like Jakarta Batch?

**Comment by rmannibucau** [comment]
AFAIK jakarta compliance defined profiles already making part optional and specs are free to do the same. Generally while passing the full suite in an ee server it is sufficient - which means spring batch can pass all tck in tomee for ex - but nothing prevents specs to add cases, will just require some more site work yo explicit that but nothing crazy.
There is no "it is used in jakarta so cant do anything outside jakarta" rule, in particular since it is an eclipse project now so could theorically take even more freedom.

**Comment by scottkurz** [comment]
I'm confused about the Jakarta processes so sent this email to the spec project leads ML: https://www.eclipse.org/lists/jakartaee-spec-project-leads/msg00738.html

**Comment by scottkurz** [comment]
Seems we're backing off of this approach for now, so closing this.
