### ISSUE TITLE
Update sigtest dependency 

### ISSUE THREAD

**Issue by scottkurz** [eclipse-ee4j/batch-tck#23]
Potentially use something like: 
https://search.maven.org/artifact/org.netbeans.tools/sigtest-maven-plugin/1.4/maven-plugin

since the version we use now from  net.java.sigtest
3.0-b12-v20140219  isn't very official-looking.

**Comment by OndroMih** [comment]
I think it's even better to turn the signature test into a unit test, so that it can be executed directly on the implementation with the same configuration as the rest of the tests. Then we don't need any special setup in maven.

The Jakarta TCK does it already, here's an example JavaEESigTest: https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/signaturetest/javaee/JavaEESigTest.java. It runs the functionality of https://search.maven.org/artifact/org.netbeans.tools/sigtest-maven-plugin/1.4/maven-plugin directly via Java API and not as a maven plugin. This is implemented in https://github.com/eclipse-ee4j/jakartaee-tck/blob/605de32c7ec214e7f5fe1a640905a1bf766d49f9/src/com/sun/ts/tests/signaturetest/SigTestDriver.java#L165, which uses the `com.sun.tdk.signaturetest.SignatureTest` class from the Maven plugin directly from Java code.

**Comment by scottkurz** [comment]
Another reference is the work here: https://github.com/eclipse-ee4j/jaxb-tck/pull/58 to support JDK12+ executions

**Comment by scottkurz** [comment]
> I think it's even better to turn the signature test into a unit test, so that it can be executed directly on the implementation with the same configuration as the rest of the tests. Then we don't need any special setup in maven.

I'm sorry, I didn't really notice Ondro's comment until now.    

That doesn't strike me as obviously better.   Or maybe it does seem better if the step of setting up a classpath is no more than setting up your Maven dependencies.     But from our past experience, I wonder if we have to offer a bit more fine-grained control, e.g. I have this set of dependencies on my compile classpath but only validate signatures against this other classpath.. so the user is still doing a custom configuration of their POM.

Maybe I'm just missing what this looks like.   If someone wants to do a PR it'd be interesting.

For now, I'm going to assume we're proceeding with using the netbeans maven plugin.

**Comment by scottkurz** [comment]
Closing. This now seems obsolete.
